```{r}
library(here)
library(tidyverse)
library(sf)
library(stars)
library(tmap)
```

```{r}
ei_points <- st_read(here("Weekly_Discussions", "week1", "data", "easter_island", "ei_points.gpkg")) |> 
  filter(type == "volcano")
ei_elev <- read_stars(here("Weekly_Discussions", "week1","data", "easter_island", "ei_elev.tif"))
ei_borders <- st_read(here("Weekly_Discussions", "week1","data", "easter_island", "ei_border.gpkg"))
ei_roads <- st_read(here("Weekly_Discussions", "week1","data", "easter_island", "ei_roads.gpkg"))
```

```{r}
# Add Easter Island vector in default gray
tm_shape(ei_borders) +
    tm_borders() +
# Set general map layout options
    tm_layout(main.title =  "Easter Island")
```

```{r}
tm_shape(ei_elev) +
    tm_raster(col.scale = tm_scale_continuous(values = "-rd_yl_gn"), # tm_scale_continuous allows for a smooth colour gradient
            col.legend = tm_legend("Elevation (m asl)")) +
    tm_shape(ei_borders) +
        tm_borders()
```

Adding roads and volcanoes
```{r}
tm_shape(ei_elev) +
    tm_raster(col.scale = tm_scale_continuous(values = "-rd_yl_gn"), # tm_scale_continuous allows for a smooth colour gradient
            col.legend = tm_legend("Elevation (m asl)")) +
tm_shape(ei_borders) +
    tm_borders() +
tm_shape(ei_roads) +
    tm_lines() + # use line string since roads are lines
tm_shape(ei_points) +
    tm_symbols(shape = 24, # point-shape code 24 is a filled triangle (classic volcano symbol)
                size = "elevation", # scale size by the variable in quotes
                size.legend = tm_legend("Volcanoes (m asl)"))
```

Multiple Object Map
```{r}
ei_map <- tm_shape(ei_elev) +
    tm_raster(col.scale = tm_scale_continuous(values = "-rd_yl_gn"), # tm_scale_continuous allows for a smooth colour gradient
            col.legend = tm_legend("Elevation (m asl)")) +
tm_shape(ei_borders) +
    tm_borders() +
tm_shape(ei_roads) +
    tm_lines() +
tm_shape(ei_points) +
    tm_symbols(shape = 24,
                size = "elevation",
                size.legend = tm_legend("Volcanoes (m asl)")) +
tm_compass(position = c("right", "top")) +
tm_scalebar() +
tm_title("Easter Island")
```

Make it interactive

```{r}
tmap_mode("view")
ei_map
```

Try with ggplot
